// GENERATED by tools/sync-a11y-config.mjs — edit tools/eslint.a11y.mjs instead.
import jsxA11y from "eslint-plugin-jsx-a11y";
import tsParser from "@typescript-eslint/parser";

/**
 * Source files carry `eslint-disable` comments naming rules from the TypeScript,
 * Next and React Hooks plugins. ESLint treats a directive that names an unknown
 * rule as an error, so those plugins are registered here — with none of their
 * rules switched on — purely so the names resolve. Without this the report
 * fills with complaints about comments rather than accessibility.
 */
const companions = {};
for (const [key, id] of [
  ["@typescript-eslint", "@typescript-eslint/eslint-plugin"],
  ["@next/next", "@next/eslint-plugin-next"],
  ["react-hooks", "eslint-plugin-react-hooks"],
]) {
  try {
    const mod = await import(id);
    companions[key] = mod.default ?? mod;
  } catch {
    // not installed in this project; its directives will simply not appear
  }
}

/**
 * Accessibility-only lint.
 *
 * Deliberately standalone — it registers the plugin and parser itself rather
 * than extending the Next preset. Two reasons: the preset also reports a large
 * backlog of `no-explicit-any` across the API routes, and an accessibility
 * regression would be lost in it; and the projects are on different versions of
 * eslint-config-next, one of which does not expose the ESM entry point the
 * others do.
 *
 * Rules were chosen against what actually went wrong here — labels sitting
 * beside a field without being attached to it, controls with no accessible
 * name, click handlers on plain divs — and are errors so the drift cannot creep
 * back quietly.
 *
 * Not enabled: jsx-a11y/control-has-associated-label. It inspects the control
 * and cannot follow a htmlFor/id pairing to the label beside it, so it reported
 * 36 correctly-labelled fields as unlabelled. label-has-associated-control
 * checks the same relationship from the side that can see it.
 */
export default [
  {
    ignores: [
      "**/.next/**",
      "**/out/**",
      "**/build/**",
      "**/node_modules/**",
      "**/next-env.d.ts",
    ],
  },
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    // The companion rules are registered but switched off, so their disable
    // comments read as unused. That is expected here and is not a finding.
    linterOptions: { reportUnusedDisableDirectives: "off" },
    plugins: { "jsx-a11y": jsxA11y, ...companions },
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      // a label points at the control it names
      "jsx-a11y/label-has-associated-control": [
        "error",
        { assert: "either", depth: 4 },
      ],

      // anything clickable is reachable and operable from the keyboard
      "jsx-a11y/click-events-have-key-events": "error",
      "jsx-a11y/interactive-supports-focus": "error",

      // Scoped to activation handlers on purpose. Hovering is not something a
      // keyboard does, and a decorative hover effect — a skill icon that lifts,
      // an animation that reacts to the pointer — has nothing to activate. The
      // default handler list drags those in and buries the real findings.
      // Dragging is likewise mouse-only; where it changes data, the keyboard
      // path has to be a real control, which is a feature rather than an
      // attribute (see the kanban note in the README).
      "jsx-a11y/no-static-element-interactions": [
        "error",
        { handlers: ["onClick", "onMouseDown", "onMouseUp", "onKeyPress", "onKeyDown", "onKeyUp"] },
      ],
      "jsx-a11y/no-noninteractive-element-interactions": [
        "error",
        { handlers: ["onClick", "onMouseDown", "onMouseUp", "onKeyPress", "onKeyDown", "onKeyUp"] },
      ],
      "jsx-a11y/tabindex-no-positive": "error",
      "jsx-a11y/no-autofocus": ["error", { ignoreNonDOM: true }],

      // names and roles that assistive technology depends on
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-has-content": "error",
      "jsx-a11y/anchor-is-valid": "error",
      "jsx-a11y/heading-has-content": "error",
      "jsx-a11y/html-has-lang": "error",
      "jsx-a11y/iframe-has-title": "error",
      "jsx-a11y/aria-props": "error",
      "jsx-a11y/aria-proptypes": "error",
      "jsx-a11y/aria-role": "error",
      "jsx-a11y/aria-unsupported-elements": "error",
      "jsx-a11y/role-has-required-aria-props": "error",
      "jsx-a11y/role-supports-aria-props": "error",
      "jsx-a11y/no-redundant-roles": "error",
      "jsx-a11y/scope": "error",
    },
  },
];
